### ISSUE TITLE
[Feature] - Improve Footer (remove number from desktop site)

### ISSUE THREAD

**Issue by thevaidik** [Swipe-industries/luxswipe-front#21]

**Comment by rajputdivyanshu81** [comment]
jo sohail sir  ne figma mai design kiya hai vhi wala add krna hai ??

**Comment by thecodephilic-guy** [comment]
Yup, that one with slight variation

**Comment by rajputdivyanshu81** [comment]
local setup mai fork krk krna hai ya direcly clone krk bhi pr sent kr sakte hai
