### ISSUE TITLE
[Bug] - After logged in , site doesn't show user is already loggedin during new sessions.

### ISSUE THREAD

**Issue by thevaidik** [Swipe-industries/luxswipe-front#24]
If we directly go to out homepage ex - luxswipe.in/thevaidik . It shows logged in. Yet on the homepage of site it doesn't. Again probably a UI issue

**Comment by thevaidik** [comment]
This one is priority

**Comment by thecodephilic-guy** [comment]
I'm on it, right now working on adding the functionality of editing user profile.

**Comment by thecodephilic-guy** [comment]
It's done
